SELECT CIU.NOMBRE
FROM CIUDADANO CIU, VOTACIONCANDIDATO VC, ESCANDIDATO ESCAN
WHERE CIU.DNI = ESCAN.DNI AND VC.idEleccion = ESCAN.idEleccion AND 
	VC.idEleccion IN 
		(SELECT idEleccion
		FROM VOTACIONCANDIDATO
		WHERE año >= ALL( SELECT año
						  FROM VOTACIONCANDIDATO ))

	AND NOT EXIST (
		SELECT CIU2.NOMBRE
		FROM CIUDADANO CIU2, ESCANDIDATO ESCAN2
		WHERE CIU.DNI != CIU2.DNI --PEDIMOS QUE SEAN PERSONAS DISTINTAS 
		AND CIU2.DNI = ESCAN2.DNI --JOIN
		AND VC.idEleccion = ESCAN2.idEleccion --EN LA MISMA ELECCION
		AND ESCAN2.CANTVOTOS >= ESCAN.CANTVOTOS) -- QUE TENGA MAS VOTOS QUE YO

----------------------------------

SELECT CEN.DIRECCION, CIU.DNI
FROM VOTA V, CIUDADANO C, MESA M, CENTRO CEN
WHERE V.IDMESA = M.IDMESA
AND M.IDCENTRO = CEN.IDCENTRO
AND CIU.DNI IN (SELECT CIU1.DNI
				FROM CIUDADANO CIU1, VOTA V1, MESA M1, CENTRO CIU1
				WHERE V1.IDMESA = M1.IDMESA
				AND M1.IDCENTRO = CEN.IDCENTRO
				ORDER BY HORA DESC
				LIMIT 5)

-----------------------------------

SELECT PP.NOMBRE
FROM PARTIDO_POLITICO PP AFILIA A, CIUDADANO CIU, ESCANDIDATO EC, SEVOTAPOR VP, CARGO CANTVOTOS
WHERE PP.IDPARTIDO = A.IDPARTIDO
AND CIU.DNI = A.DNI
AND CIU.DNI = EC.DNI
AND EC.IDELECCION (..FALTA! ULTIMAS 5 ELECCIONES)
AND VP.IDCARGO = C.IDCARGO
AND C.NOMBRE = 'GOBERNADOR'
AND EC.VOTOS > (SELECT SUM(VOTOS)/5
				FROM ESCANDIDATO
				WHERE IDELECCION = EC.IDELECCION)